### PR TITLE
*^ memory/vector._refs host pointer

### PR DESCRIPTION
**Pull request by radonnachie**
fixing seg-faults seen under WSL2 docker runs by @radonnachie

### CODE REVIEW

**Comment by radonnachie** [comment]
of course, happy to discuss/adjust... 

Any strong reason to have a single U64 reside on the GPU, especially when it's just a counter and not an obvious bottleneck?

Not sure why it failed for me, but I think it's quite reasonable to keep the _refs on the host.

Only thing I thought you'd prefer is a `static_cast<U64*>` instead of the `new`, but maybe you agree it's more inline with C++ standards this way.

**Comment by radonnachie** [comment]
ah, I had bumped the wrong thing in the wrong place... please squash commits 👍

**Comment by luigifcruz** [comment]
The runner appears to be down. Investigating...

**Comment by luigifcruz** [comment]
Thanks for this! Had a problem with the CI but I patched it.

**Pull request merged**
